apiVersion: v1
kind: ConfigMap
metadata:
  name: app-conf
data:
  __init__.py: |
    import os

    DB_TYPE = os.environ.get('DB_TYPE')
    DB_USER = os.environ.get('DB_USER')
    DB_PASSWORD = os.environ.get('DB_PASSWORD')
    DB_HOST = os.environ.get('DB_HOST')
    DB_PORT = os.environ.get('DB_PORT')
    DB_INST = os.environ.get('DB_INST')

    class Config(object):
        SQLALCHEMY_DATABASE_URI = DB_TYPE + ':///' + DB_USER + ":" DB_PASSWORD + "@" + DB_HOST + ":" + DB_PORT + "/" + DB_INST